allowBuilds:
  sharp: set this to true or false
  unrs-resolver: set this to true or false
onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
  - supabase
  - unrs-resolver
verifyDepsBeforeRun: false
